import { useState } from 'react';

type Props = { mode: 'login' | 'register'; onModeChange: (mode: 'login' | 'register') => void; onSubmit: (data: { fullName?: string; email: string; password: string }) => Promise<void> };

export function AuthPanel({ mode, onModeChange, onSubmit }: Props) {
  const [form, setForm] = useState({ fullName: '', email: '', password: '' });
  const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); try { await onSubmit(form); } finally { setBusy(false); } };
  return <section className="auth-layout"><div className="auth-story"><span className="eyebrow">Một tài khoản · cả hành trình</span><h1>Học bằng tai.<br /><em>Nhớ bằng tim.</em></h1><p>Để VRhythm đi cùng bạn từ nốt nhạc đầu tiên đến giai điệu của riêng mình.</p><div className="quote-mark">“</div><p className="quote">Âm nhạc truyền thống không ở phía sau chúng ta. Nó đang chờ được nghe lại.</p></div><div className="auth-card"><div className="auth-tabs"><button className={mode === 'login' ? 'active' : ''} onClick={() => onModeChange('login')}>Đăng nhập</button><button className={mode === 'register' ? 'active' : ''} onClick={() => onModeChange('register')}>Tạo tài khoản</button></div><h2>{mode === 'login' ? 'Chào mừng trở lại' : 'Bắt đầu hành trình'}</h2><p className="muted">{mode === 'login' ? 'Tiếp tục nơi bạn đã dừng lại.' : 'Chọn nhạc cụ và học theo nhịp của bạn.'}</p><form onSubmit={submit}>{mode === 'register' && <label>Họ và tên<input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} placeholder="Nguyễn Văn An" /></label>}<label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="ban@example.com" /></label><label>Mật khẩu<input required minLength={6} type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="Tối thiểu 6 ký tự" /></label><button className="primary full" disabled={busy}>{busy ? 'Đang kết nối...' : mode === 'login' ? 'Đăng nhập' : 'Tạo tài khoản'}</button></form><div className="divider"><span>hoặc</span></div><button className="social-button">G Tiếp tục với Google</button></div></section>;
}
